### ISSUE TITLE
[BUG] Report bug

### ISSUE THREAD

**Issue by custer7** [vuejs/babel-plugin-jsx#724] opened 2024-09-06 03:26 UTC
### 🐛 Bug description

"resolveDirective" is imported from external module "vue" but never used
<img width="641" alt="image" src="https://github.com/user-attachments/assets/6668e35c-4009-4272-b8bb-aab250e89c88">

<img width="777" alt="image" src="https://github.com/user-attachments/assets/419beefe-019c-4e6e-92d2-f8ed6cfa9663">
Delete the vuetify related settings and it will be normal.

**Comment by sxzz** [comment] 2024-09-06 08:42
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed** 2024-09-11 11:21 UTC
